---
title: "Differential expression analysis"
author: "Marco Tello"
date: "2024-02-14"
output: github_document
---

```{r setup, include=FALSE}
# Differential expression tools
library(DESeq2)
# Data format 
library(data.table)
library(stringr)
```

# Standard DEA

First we perform differential expression analysis utilizing only the differences between diets to identify DEGs. 

```{r read data}

# Read expression data
exp_df <- fread(file = "~/GitHub/CellDecon/input/rnaseq/filtered_counts_Rnorv6.tsv")
# Create expression matrix object
rna_mat <- as.matrix(exp_df[, .SD, .SDcols = !c("ENSEMBLID", "GeneSymbol", "Length")])
rownames(rna_mat) <- exp_df$ENSEMBLID
# Build metadata
condition <- str_replace(colnames(rna_mat), pattern = "_\\d+", replacement = "") 
coldat <- data.frame(Diet = as.factor(condition),
                     Sample = colnames(rna_mat), 
                     stringsAsFactors = TRUE)
coldat$Diet <- relevel(coldat$Diet, ref = "CSAA")

```


Use DESeq2 to identify differences between diets 

```{r}
# Define DESeq2 object
deseq_rna_base <- DESeqDataSetFromMatrix(countData = rna_mat,
                                         colData = coldat,
                                         design = ~ Diet)
# Perform differential expression
deseq_rna_base <- DESeq(deseq_rna_base)
# Extract results
RNA_DE_PTS_vs_CSAA <- results(deseq_rna_base, 
                              name="Diet_PTS_vs_CSAA",
                              pAdjustMethod = "BH", 
                              alpha = 0.05)
# Add gene name column (ENSEMBL)
RNA_DE_PTS_vs_CSAA <- cbind(rownames(RNA_DE_PTS_vs_CSAA),
                            RNA_DE_PTS_vs_CSAA)
names(RNA_DE_PTS_vs_CSAA)[1] <- "ENSEMBLID"
# Add info about Genesymbol
RNA_DE_PTS_vs_CSAA <- merge.data.table(x = exp_df[, .SD, .SDcols = c("ENSEMBLID", "GeneSymbol")],
                                       y = RNA_DE_PTS_vs_CSAA,
                                       by = "ENSEMBLID")
```

```{r}
# Output file
out_file <- "~/GitHub/CellDecon/output/DESeq2/base_DESeq_full.tsv"
if(!file.exists(out_file)){
  fwrite(RNA_DE_PTS_vs_CSAA, file = out_file, 
         append = FALSE, quote = FALSE, 
         sep = '\t', na = "",
         row.names = FALSE, col.names = TRUE)
}

out_file <- "~/GitHub/CellDecon/output/DESeq2/base_DEG.tsv"
if(!file.exists(out_file)){
  fwrite(RNA_DE_PTS_vs_CSAA[round(padj, 2) <= 0.05], 
         file = out_file, 
         append = FALSE, quote = FALSE, 
         sep = '\t', na = "",
         row.names = FALSE, col.names = TRUE)
}
```



# Cell deconvolution results


First, we read the calculated cell fractions. 

```{r}
# Read CIBERSORTx matrix
fractions <- fread("~/GitHub/CellDecon/output/CIBERSORTx/fractions_Sone2one_Mone2one_newExp.txt")
# Format column names
names(fractions) <- str_replace(str_replace(names(fractions), 
                                            pattern = " Lineage", 
                                            replacement = ""),
                                pattern = " ", 
                                replacement = "")
fractions <- fractions[, .SD, .SDcols = c("Mixture","TCell","Macrophage","BCell","Neutrophil")]
fractions[, Mixture := gsub(pattern = "-", replacement = ".", x = Mixture)]
fractions <- data.table(fractions, key = "Mixture")

# Verify that samples are in the same order as the input rna_mat
fractions_sub <- fractions[colnames(rna_mat)]

# Format sample metadata 
coldat_decon <- merge.data.table(x = coldat, y = fractions_sub, 
                                 by.x = "Sample", by.y = "Mixture")
coldat_decon$Diet <- relevel(coldat_decon$Diet, ref = "CSAA")
coldat_decon <- data.table(coldat_decon, key = "Sample")

```


Then we identify the differentially expressed genes incorporating the cell fractions. 

```{r}
# Build DESeq object to perform the analysis
deseq_rna_decon <- DESeqDataSetFromMatrix(countData = rna_mat,
                                          colData = coldat_decon,
                                          design = ~ Diet + TCell + Macrophage + BCell)
# Perform differential expression
deseq_rna_decon <- DESeq(deseq_rna_decon)

# Extract results
decon_RNA_DE_PTS_vs_CSAA <- results(deseq_rna_decon, 
                                    name="Diet_PTS_vs_CSAA",
                                    pAdjustMethod = "BH", 
                                    alpha = 0.05)

# Add gene name column (ENSEMBL)
decon_RNA_DE_PTS_vs_CSAA <- cbind(rownames(decon_RNA_DE_PTS_vs_CSAA),
                                  decon_RNA_DE_PTS_vs_CSAA)
names(decon_RNA_DE_PTS_vs_CSAA)[1] <- "ENSEMBLID"

# Add info about Genesymbol
decon_RNA_DE_PTS_vs_CSAA <- merge.data.table(x = exp_df[, .SD, 
                                                        .SDcols = c("ENSEMBLID", "GeneSymbol")],
                                             y = decon_RNA_DE_PTS_vs_CSAA,
                                             by = "ENSEMBLID")
```

```{r}

out_file <- "~/GitHub/CellDecon/output/DESeq2/decon_DESeq_full.tsv"
if(!file.exists(out_file)){
  fwrite(decon_RNA_DE_PTS_vs_CSAA, file = out_file, 
         append = FALSE, quote = FALSE, 
         sep = '\t', na = "",
         row.names = FALSE, col.names = TRUE)
}

out_file <- "~/GitHub/CellDecon/output/DESeq2/decon_DEG.tsv"
if(!file.exists(out_file)){
  fwrite(decon_RNA_DE_PTS_vs_CSAA[round(padj, 2) <= 0.05], 
         file = out_file, 
         append = FALSE, quote = FALSE, 
         sep = '\t', na = "",
         row.names = FALSE, col.names = TRUE)
}
```
